-- Migration 20260804020000_credit_reservations.sql
-- Credit reservation primitives, canonical DB price derivation, server-owned TTL,
-- DB ownership & story-mode enforcement, EXPIRED reservation re-activation semantics,
-- generic financial capture (without granting PAID_START entitlement), and ACL hardening.

-- 1) Table credit_reservations
create table if not exists public.credit_reservations (
  id               uuid primary key default gen_random_uuid(),
  user_id          uuid not null references auth.users(id) on delete cascade,
  story_id         text not null,
  chapter_number   integer null,
  reservation_kind text not null check (reservation_kind in ('CHAPTER_UNLOCK', 'STORY_START')),
  amount           integer not null check (amount > 0),
  status           text not null default 'ACTIVE' check (status in ('ACTIVE', 'CAPTURED', 'RELEASED', 'EXPIRED')),
  ref              text not null unique,
  created_at       timestamptz not null default now(),
  expires_at       timestamptz not null,
  updated_at       timestamptz not null default now()
);

create index if not exists credit_reservations_user_active_idx
  on public.credit_reservations (user_id, status)
  where status = 'ACTIVE';

-- Logical uniqueness constraint: prevent duplicate ACTIVE reservations for same user/story/chapter
create unique index if not exists credit_reservations_chapter_active_uniq_idx
  on public.credit_reservations (user_id, story_id, chapter_number, reservation_kind)
  where status = 'ACTIVE' and reservation_kind = 'CHAPTER_UNLOCK';

create unique index if not exists credit_reservations_story_start_active_uniq_idx
  on public.credit_reservations (user_id, story_id, reservation_kind)
  where status = 'ACTIVE' and reservation_kind = 'STORY_START';

-- Enable RLS and DO NOT add policies for anon/authenticated (strictly service_role only)
alter table public.credit_reservations enable row level security;

-- 2) RPC: available_credit_balance_v1
-- Ledger balance minus sum of ACTIVE, UNEXPIRED reservations.
create or replace function public.available_credit_balance_v1(p_user_id uuid)
returns integer
language sql stable security definer set search_path = public
as $$
  select coalesce(
    (select sum(delta) from public.credit_ledger where user_id = p_user_id),
    0
  )::int - coalesce(
    (select sum(amount) from public.credit_reservations
     where user_id = p_user_id
       and status = 'ACTIVE'
       and expires_at > clock_timestamp()),
    0
  )::int;
$$;

-- Helper: Lazy expiry for past-due active reservations under user advisory lock
create or replace function public.expire_user_reservations_lazy_v1(p_user_id uuid)
returns void
language plpgsql security definer set search_path = public
as $$
begin
  update public.credit_reservations
  set status = 'EXPIRED',
      updated_at = clock_timestamp()
  where user_id = p_user_id
    and status = 'ACTIVE'
    and expires_at <= clock_timestamp();
end;
$$;

-- 3) RPC: reserve_chapter_unlock_v1
-- Reserve 8 credits for chapter unlock. Checks DB ownership & story mode.
-- Handles re-activation of EXPIRED reservation for exact same chapter under user lock without creating duplicate holds.
create or replace function public.reserve_chapter_unlock_v1(
  p_user_id        uuid,
  p_story_id       text,
  p_chapter_number integer
) returns jsonb
language plpgsql security definer set search_path = public
as $$
declare
  v_cost             integer;
  v_available        integer;
  v_canonical_ref    text;
  v_existing         public.credit_reservations%rowtype;
  v_story_owner      uuid;
  v_story_visibility text;
  c_ttl_seconds      constant integer := 1800; -- 30 minutes workflow budget safety reserve
begin
  if p_user_id is null or p_story_id is null or p_chapter_number is null or p_chapter_number < 1 then
    raise exception 'reserve_chapter_unlock_v1: invalid arguments';
  end if;

  perform pg_advisory_xact_lock(hashtext(p_user_id::text));

  -- Ownership verification
  select owner_user_id, visibility into v_story_owner, v_story_visibility
  from public.stories
  where id = p_story_id;

  if not found or v_story_owner is distinct from p_user_id then
    return jsonb_build_object('ok', false, 'reason', 'NOT_STORY_OWNER');
  end if;

  -- Canonical price from DB feature_credit_costs (fallback 8)
  select coalesce(
    (select credits_required from public.feature_credit_costs where feature_key = 'chapter_unlock' and is_active = true limit 1),
    8
  ) into v_cost;

  -- Canonical operation key generated by DB
  v_canonical_ref := 'chapter-reservation:' || p_user_id::text || ':' || p_story_id || ':' || p_chapter_number::text;

  perform public.expire_user_reservations_lazy_v1(p_user_id);

  select * into v_existing from public.credit_reservations where ref = v_canonical_ref;

  if found then
    if v_existing.status = 'ACTIVE' and v_existing.expires_at > clock_timestamp() then
      return jsonb_build_object('ok', true, 'status', 'RESERVED', 'ref', v_canonical_ref, 'replayed', true);
    end if;
    if v_existing.status = 'CAPTURED' then
      return jsonb_build_object('ok', true, 'status', 'ALREADY_CAPTURED', 'ref', v_canonical_ref);
    end if;
    -- Existing reservation is EXPIRED or RELEASED -> re-activation path under user lock
  end if;

  v_available := public.available_credit_balance_v1(p_user_id);
  if v_available < v_cost then
    return jsonb_build_object('ok', false, 'reason', 'INSUFFICIENT_CREDITS', 'available', v_available, 'required', v_cost);
  end if;

  insert into public.credit_reservations (
    user_id, story_id, chapter_number, reservation_kind, amount, status, ref, expires_at
  ) values (
    p_user_id, p_story_id, p_chapter_number, 'CHAPTER_UNLOCK', v_cost, 'ACTIVE', v_canonical_ref,
    clock_timestamp() + (c_ttl_seconds * interval '1 second')
  ) on conflict (ref) do update set
    status = 'ACTIVE',
    amount = v_cost,
    expires_at = clock_timestamp() + (c_ttl_seconds * interval '1 second'),
    updated_at = clock_timestamp();

  return jsonb_build_object('ok', true, 'status', 'RESERVED', 'ref', v_canonical_ref, 'cost', v_cost, 'reactivated', found);
end;
$$;

-- 4) RPC: reserve_story_start_v1
-- Reserve 24 credits for story start (#2+). Checks DB ownership AND story-mode eligibility.
-- Handles re-activation of EXPIRED reservation under user lock.
-- Sets story commercial_origin to PENDING_PAID_START.
create or replace function public.reserve_story_start_v1(
  p_user_id  uuid,
  p_story_id text
) returns jsonb
language plpgsql security definer set search_path = public
as $$
declare
  v_cost             integer;
  v_available        integer;
  v_canonical_ref    text;
  v_existing         public.credit_reservations%rowtype;
  v_story_owner      uuid;
  v_story_visibility text;
  c_ttl_seconds      constant integer := 1800;
begin
  if p_user_id is null or p_story_id is null then
    raise exception 'reserve_story_start_v1: invalid arguments';
  end if;

  perform pg_advisory_xact_lock(hashtext(p_user_id::text));

  -- Ownership and story mode verification
  select owner_user_id, visibility into v_story_owner, v_story_visibility
  from public.stories
  where id = p_story_id;

  if not found or v_story_owner is distinct from p_user_id then
    return jsonb_build_object('ok', false, 'reason', 'NOT_STORY_OWNER');
  end if;

  if v_story_visibility not in ('private', 'unlisted') or p_story_id like 'demo:%' then
    return jsonb_build_object('ok', false, 'reason', 'NOT_ELIGIBLE_STORY_MODE');
  end if;

  -- Canonical price from DB feature_credit_costs (fallback 24)
  select coalesce(
    (select credits_required from public.feature_credit_costs where feature_key = 'story_start' and is_active = true limit 1),
    24
  ) into v_cost;

  -- Canonical operation key generated by DB
  v_canonical_ref := 'story-start:' || p_user_id::text || ':' || p_story_id;

  perform public.expire_user_reservations_lazy_v1(p_user_id);

  select * into v_existing from public.credit_reservations where ref = v_canonical_ref;

  if found then
    if v_existing.status = 'ACTIVE' and v_existing.expires_at > clock_timestamp() then
      return jsonb_build_object('ok', true, 'status', 'RESERVED', 'ref', v_canonical_ref, 'replayed', true);
    end if;
    if v_existing.status = 'CAPTURED' then
      return jsonb_build_object('ok', true, 'status', 'ALREADY_CAPTURED', 'ref', v_canonical_ref);
    end if;
  end if;

  v_available := public.available_credit_balance_v1(p_user_id);
  if v_available < v_cost then
    return jsonb_build_object('ok', false, 'reason', 'INSUFFICIENT_CREDITS', 'available', v_available, 'required', v_cost);
  end if;

  insert into public.credit_reservations (
    user_id, story_id, chapter_number, reservation_kind, amount, status, ref, expires_at
  ) values (
    p_user_id, p_story_id, 1, 'STORY_START', v_cost, 'ACTIVE', v_canonical_ref,
    clock_timestamp() + (c_ttl_seconds * interval '1 second')
  ) on conflict (ref) do update set
    status = 'ACTIVE',
    amount = v_cost,
    expires_at = clock_timestamp() + (c_ttl_seconds * interval '1 second'),
    updated_at = clock_timestamp();

  -- Set pre-capture pending state on story
  update public.stories
  set commercial_origin = 'PENDING_PAID_START'
  where id = p_story_id and (commercial_origin is null or commercial_origin = 'PENDING_PAID_START');

  return jsonb_build_object('ok', true, 'status', 'RESERVED', 'ref', v_canonical_ref, 'cost', v_cost, 'reactivated', found);
end;
$$;

-- 5) RPC: capture_credit_reservation_v1
-- FINANCIAL PRIMITIVE ONLY. Converts ACTIVE reservation to CAPTURED and debits credit_ledger using CANONICAL debit ref:
--  - For CHAPTER_UNLOCK: ledger ref = 'unlock:' || story_id || ':' || chapter_number
--  - For STORY_START: ledger ref = 'story-start:' || story_id
-- CRITICAL REQUIREMENT 2: Generic financial capture MUST NOT update stories.commercial_origin to PAID_START.
-- The transition PENDING_PAID_START -> PAID_START is strictly deferred to Bab 1 publication success in Phase 2.
create or replace function public.capture_credit_reservation_v1(
  p_ref text
) returns text
language plpgsql security definer set search_path = public
as $$
declare
  v_res           public.credit_reservations%rowtype;
  v_canonical_ref text;
  v_reason        text;
  v_spend_status  text;
begin
  if p_ref is null or trim(p_ref) = '' then
    raise exception 'capture_credit_reservation_v1: invalid arguments';
  end if;

  select * into v_res
  from public.credit_reservations
  where ref = p_ref
  for update;

  if not found then
    return 'not_found';
  end if;

  perform pg_advisory_xact_lock(hashtext(v_res.user_id::text));

  -- Lazy cleanup
  perform public.expire_user_reservations_lazy_v1(v_res.user_id);

  select * into v_res from public.credit_reservations where id = v_res.id for update;

  if v_res.status = 'CAPTURED' then
    return 'duplicate';
  end if;

  if v_res.status = 'EXPIRED' or v_res.expires_at <= clock_timestamp() then
    update public.credit_reservations set status = 'EXPIRED', updated_at = clock_timestamp() where id = v_res.id;
    return 'expired';
  end if;

  if v_res.status <> 'ACTIVE' then
    return 'not_active';
  end if;

  -- Canonical debit ref mapping
  if v_res.reservation_kind = 'CHAPTER_UNLOCK' then
    v_canonical_ref := 'unlock:' || v_res.story_id || ':' || coalesce(v_res.chapter_number::text, '1');
    v_reason := 'unlock_chapter';
  elsif v_res.reservation_kind = 'STORY_START' then
    v_canonical_ref := 'story-start:' || v_res.story_id;
    v_reason := 'paid_story_start';
  else
    v_canonical_ref := 'capture:' || p_ref;
    v_reason := 'reservation_capture';
  end if;

  v_spend_status := public.spend_credits_v1(
    v_res.user_id,
    v_canonical_ref,
    v_res.amount,
    v_reason
  );

  if v_spend_status not in ('ok', 'duplicate') then
    return 'spend_failed:' || v_spend_status;
  end if;

  -- NOTE: Generic financial capture intentionally DOES NOT alter stories.commercial_origin = 'PAID_START'.
  -- That transition is strictly reserved for the authoritative fenced Bab 1 publication transaction in Phase 2.

  update public.credit_reservations
  set status = 'CAPTURED',
      updated_at = clock_timestamp()
  where id = v_res.id;

  return 'ok';
end;
$$;

-- 6) RPC: release_credit_reservation_v1
-- Releases an ACTIVE credit hold.
create or replace function public.release_credit_reservation_v1(
  p_ref text
) returns text
language plpgsql security definer set search_path = public
as $$
declare
  v_res public.credit_reservations%rowtype;
begin
  if p_ref is null or trim(p_ref) = '' then
    raise exception 'release_credit_reservation_v1: invalid arguments';
  end if;

  select * into v_res
  from public.credit_reservations
  where ref = p_ref
  for update;

  if not found then
    return 'not_found';
  end if;

  perform pg_advisory_xact_lock(hashtext(v_res.user_id::text));

  if v_res.status = 'RELEASED' then
    return 'duplicate';
  end if;

  if v_res.status <> 'ACTIVE' then
    return 'not_active';
  end if;

  update public.credit_reservations
  set status = 'RELEASED',
      updated_at = clock_timestamp()
  where id = v_res.id;

  return 'ok';
end;
$$;

-- 7) SECURITY & ACL HARDENING
REVOKE ALL ON FUNCTION public.available_credit_balance_v1(uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.expire_user_reservations_lazy_v1(uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.reserve_chapter_unlock_v1(uuid, text, integer) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.reserve_story_start_v1(uuid, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.capture_credit_reservation_v1(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.release_credit_reservation_v1(text) FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.available_credit_balance_v1(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.expire_user_reservations_lazy_v1(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.reserve_chapter_unlock_v1(uuid, text, integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.reserve_story_start_v1(uuid, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.capture_credit_reservation_v1(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.release_credit_reservation_v1(text) TO service_role;
