-- M10-E E5 Blueprint Resolutions
-- Immutable authoritative disposition result. Writes occur only through RPC/service role.

CREATE TABLE public.blueprint_resolutions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  story_id text NOT NULL REFERENCES public.blueprint_queue(story_id) ON DELETE RESTRICT,
  source_event_id bigint NOT NULL REFERENCES public.story_events(id) ON DELETE RESTRICT,
  disposition text NOT NULL
    CHECK (disposition IN ('REJECT_BLOCK', 'RETRY_ALLOW', 'UNBLOCK_PERMIT')),
  reviewer_uid uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  reason_text text NOT NULL,
  chapter_numbers integer[] NOT NULL,
  request_fingerprint text NOT NULL UNIQUE,
  result_unblock_proof text,
  result_proof_id uuid,
  result_chapter_version_pairs jsonb NOT NULL,
  created_at timestamptz NOT NULL,
  CONSTRAINT blueprint_resolutions_result_shape_check CHECK (
    (disposition = 'UNBLOCK_PERMIT'
      AND result_unblock_proof IS NOT NULL
      AND result_proof_id IS NOT NULL)
    OR
    (disposition <> 'UNBLOCK_PERMIT'
      AND result_unblock_proof IS NULL
      AND result_proof_id IS NULL)
  )
);

CREATE INDEX idx_blueprint_resolutions_story_id
  ON public.blueprint_resolutions(story_id);
CREATE INDEX idx_blueprint_resolutions_created
  ON public.blueprint_resolutions(created_at DESC);

COMMENT ON TABLE public.blueprint_resolutions IS
  'Immutable authoritative disposition results for E-OPS-1';
COMMENT ON COLUMN public.blueprint_resolutions.request_fingerprint IS
  'SHA-256 fingerprint binding complete disposition request and evidence';
COMMENT ON COLUMN public.blueprint_resolutions.result_chapter_version_pairs IS
  'Persisted source/result blueprint versions; replay returns this authoritative result';

ALTER TABLE public.blueprint_resolutions ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.blueprint_resolutions FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON SEQUENCE public.blueprint_resolutions_id_seq FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT ON TABLE public.blueprint_resolutions TO service_role;
