/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AccountCommercialStates {
  created_at: Generated<Timestamp>;
  risk_state: Generated<string>;
  starter_claimed_at: Timestamp | null;
  starter_story_id: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
  welcome_credit_event_id: string | null;
  welcome_credit_granted_at: Timestamp | null;
}

export interface ActRollups {
  act_number: number;
  covers_from_chapter: number;
  covers_to_chapter: number;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  state_delta: Generated<Json>;
  story_id: string;
  summary: string;
}

export interface AdminCreditGrants {
  admin_user_id: string;
  created_at: Generated<Timestamp>;
  credits: number;
  id: Generated<string>;
  ledger_ref: string;
  reason: string;
  target_user_id: string;
}

export interface AdminGenerationAccessAudit {
  action: string;
  actor_user_id: string;
  created_at: Generated<Timestamp>;
  filter_fingerprint: string | null;
  id: Generated<string>;
  target_job_id: string | null;
  target_provider_call_id: string | null;
}

export interface AdminSettingsAuditLogs {
  admin_email: string | null;
  admin_user_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  new_value: Json;
  old_value: Json | null;
  reason: string;
  setting_area: string;
  setting_key: string;
}

export interface AdminUsers {
  created_at: Generated<Timestamp>;
  role: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface AdmobSsvEvents {
  ad_unit: Generated<string>;
  created_at: Generated<Timestamp>;
  day_jkt: Timestamp;
  reward_amount: Generated<number>;
  status: string;
  transaction_id: string;
  user_id: string | null;
}

export interface AiModelRoutes {
  created_at: Generated<Timestamp>;
  fallback_models: Generated<Json>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  max_output_tokens: number | null;
  model_id: string;
  notes: string | null;
  provider: string;
  /**
   * Optional provider reasoning effort forwarded to the model call (none|minimal|low|medium|high). Null = provider default.
   */
  reasoning_effort: string | null;
  route_version: Generated<string>;
  temperature: Numeric | null;
  updated_at: Generated<Timestamp>;
  use_case: string;
}

export interface AnalyticsEvents {
  anonymous_id: string | null;
  created_at: Generated<Timestamp>;
  event_name: string;
  id: Generated<string>;
  payload: Generated<Json>;
  user_id: string | null;
}

export interface AuthUsers {
  aud: string | null;
  created_at: Generated<Timestamp>;
  email: string | null;
  email_confirmed_at: Timestamp | null;
  encrypted_password: string | null;
  id: string;
  instance_id: string | null;
  raw_app_meta_data: Generated<Json>;
  raw_user_meta_data: Generated<Json>;
  role: string | null;
  updated_at: Generated<Timestamp>;
}

export interface BlueprintAuditLog {
  created_at: Timestamp;
  disposition: string;
  id: Generated<string>;
  reason_text: string;
  request_fingerprint: string;
  resolution_id: Int8;
  reviewer_uid: string;
  source_event_id: Int8;
  story_id: string;
}

export interface BlueprintQueue {
  act_boundary: string;
  brand_scan_hash: string | null;
  chapter_numbers: number[];
  claimed_at: Timestamp | null;
  claimed_by: string | null;
  created_at: Generated<Timestamp>;
  findings: Generated<Json>;
  lease_id: string | null;
  provider_call_id: string | null;
  retry_count: Generated<number>;
  /**
   * Required source story event; event/story consistency is enforced by e5_record_disposition
   */
  source_event_id: Int8;
  status: Generated<string>;
  story_id: string;
}

export interface BlueprintResolutions {
  chapter_numbers: number[];
  created_at: Timestamp;
  disposition: string;
  id: Generated<Int8>;
  reason_text: string;
  /**
   * SHA-256 fingerprint binding complete disposition request and evidence
   */
  request_fingerprint: string;
  /**
   * Persisted source/result blueprint versions; replay returns this authoritative result
   */
  result_chapter_version_pairs: Json;
  result_proof_id: string | null;
  result_unblock_proof: string | null;
  reviewer_uid: string;
  source_event_id: Int8;
  story_id: string;
}

export interface BlueprintValidatorAttestations {
  attestation_hash: string;
  chapter_numbers: number[];
  created_at: Generated<Timestamp>;
  ending_results: Json;
  expected_chapter_versions: Json;
  id: Generated<string>;
  reviewer_uid: string;
  source_event_id: Int8;
  spine_reveal_findings: Json;
  story_id: string;
  validator_version: string;
}

export interface BlueprintValidatorProofs {
  chapter_numbers: number[];
  /**
   * Source/result chapter-version pairs as plain jsonb
   */
  chapter_version_pairs: Json;
  created_at: Timestamp;
  disposition: string;
  ending_results: Json;
  id: Generated<string>;
  proof_hash: string;
  proof_type: string;
  proof_value: string;
  reason_text: string;
  request_fingerprint: string;
  resolution_id: Int8;
  reviewer_uid: string;
  source_event_id: Int8;
  /**
   * Canonical spine/reveal findings as plain jsonb
   */
  spine_reveal_findings: Json;
  story_id: string;
  /**
   * Full signed JSONB validator envelope for stateless E5 proofs; null only on legacy UUID-backed rows
   */
  validator_attestation: Json | null;
  /**
   * Required unique evidence identity: legacy attestation hash or SHA-256 hash of full signed JSONB envelope
   */
  validator_attestation_hash: string;
  /**
   * Nullable legacy FK retained only for authoritative pre-stateless attestation history
   */
  validator_attestation_id: string | null;
  validator_payload: Json;
  validator_version: string;
}

export interface ChapterBlueprints {
  allowed_state_delta: Generated<Json>;
  chapter_goal: Generated<string>;
  chapter_number: number;
  created_at: Generated<Timestamp>;
  forbidden_reveals: Generated<Json>;
  id: Generated<Int8>;
  introduces_characters: Generated<Json>;
  mandatory_beats: Generated<Json>;
  phase: Generated<string>;
  reconciled_from_version: number | null;
  reconciliation_reason: string | null;
  story_id: string;
  version: Generated<number>;
}

export interface ChapterGenerationCheckpoints {
  attempt_id: string;
  audit_signals_json: Json | null;
  audit_signals_version: number | null;
  /**
   * stories.canon_state_revision the delta was computed against. V3 only; writer requires exact current revision.
   */
  base_canon_revision: Int8 | null;
  blueprint_version: Int8 | null;
  canon_version: Int8 | null;
  chapter_number: number;
  /**
   * Freshness policy marker. 1 = legacy compatibility, 2 = strict non-null versions, 3 = living canon (state delta required).
   */
  checkpoint_schema_version: Generated<number>;
  choice_attempt_count: Generated<number>;
  correlation_id: string;
  created_at: Generated<Timestamp>;
  direction_fingerprint: string | null;
  expires_at: Timestamp;
  generation_mode: string | null;
  generation_policy_version: number | null;
  /**
   * Provenance: attempt_count when prose was written. Freshness uses <= current, never ===.
   */
  job_attempt_number: number | null;
  /**
   * Provenance: generation_jobs.id that produced this prose. Not a freshness equality key.
   */
  job_id: string | null;
  paragraphs_json: Json;
  prompt_contract_version: number | null;
  prose_attempt_count: Generated<number>;
  prose_fingerprint: string;
  /**
   * DB-computed SHA-256 (domain-separated) of state_delta_json. Never caller-supplied; CHECK re-derives it.
   */
  state_delta_hash: string | null;
  /**
   * Validated canonical state delta. V3 only; NULL for legacy v1/v2 rows.
   */
  state_delta_json: Json | null;
  /**
   * State delta contract version. 1 = current. V3 only.
   */
  state_delta_schema_version: number | null;
  status: string;
  /**
   * Copied from generation_jobs.story_contract_version at checkpoint creation.
   */
  story_contract_version: number | null;
  story_id: string;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface Chapters {
  choice_prompt: string | null;
  choices: Json | null;
  created_at: Generated<Timestamp>;
  number: number;
  paragraphs: Generated<Json>;
  story_id: string;
  title: string;
}

export interface ChapterStateCommits {
  /**
   * User acting on the story, when known (worker path may be NULL).
   */
  actor_user_id: string | null;
  /**
   * Pre-commit revision the delta was computed against (stories.canon_state_revision before increment).
   */
  base_canon_revision: Int8;
  chapter_number: number;
  /**
   * chapter_generation_checkpoints.attempt_id that produced the delta (sync: synthetic attempt id).
   */
  checkpoint_attempt_id: string;
  commit_version: Generated<number>;
  /**
   * Post-increment revision; must equal base_canon_revision + 1.
   */
  committed_canon_revision: Int8;
  /**
   * Attempt-run correlation, read from the locked checkpoint at publication. Never caller-supplied.
   */
  correlation_id: string;
  created_at: Generated<Timestamp>;
  generation_mode: string;
  id: Generated<string>;
  /**
   * DB-computed publication payload hash (chapter_publication_payload_hash_v1). Durable replay proof.
   */
  publication_payload_hash: string;
  /**
   * Publication payload contract version. 1 = current.
   */
  publication_payload_schema_version: Generated<number>;
  /**
   * Canonical cross-path replay result. Stored once in the commit transaction; exact replay returns it.
   */
  publication_result: Json;
  /**
   * Generation job provenance; NULL for the sync path (no generation job exists).
   */
  source_job_id: string | null;
  state_delta_hash: string;
  state_delta_json: Json;
  state_delta_schema_version: Generated<number>;
  story_id: string;
}

export interface CharacterAliases {
  alias: string;
  alias_type: Generated<string>;
  character_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  story_id: string;
}

export interface Characters {
  canonical_name: string;
  created_at: Generated<Timestamp>;
  id: string;
  introduced_chapter: Generated<number>;
  motivation: Generated<string>;
  role: Generated<string>;
  story_id: string;
}

export interface CharacterStates {
  as_of_chapter: Generated<number>;
  attributes: Generated<Json>;
  character_id: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface CharacterVoiceSheets {
  character_id: string;
  created_at: Generated<Timestamp>;
  forbidden_words: Generated<Json>;
  register: Generated<string>;
  sample_lines: Generated<Json>;
  speech_habits: Generated<Json>;
  story_id: string;
}

export interface ChoiceOutcomes {
  chapter_number: number;
  choice_id: string;
  choice_kind: Generated<string>;
  consequence: Generated<Json>;
  created_at: Generated<Timestamp>;
  effect_json: Generated<Json>;
  is_ending: Generated<boolean>;
  next_chapter_number: number | null;
  story_id: string;
}

export interface CommercialGenerationIntents {
  chapter_number: number;
  created_at: Generated<Timestamp>;
  generation_job_id: string | null;
  id: Generated<string>;
  pricing_version: string;
  quoted_credits: number;
  status: string;
  story_id: string;
  trigger_choice_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface ContentReports {
  canonical_refs: Generated<Json>;
  category: string;
  chapter_number: number;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  note: string | null;
  reporter_id: string | null;
  status: Generated<string>;
  story_id: string;
}

export interface CreditLedger {
  created_at: Generated<Timestamp>;
  delta: number;
  id: Generated<string>;
  reason: string;
  ref: string;
  user_id: string;
}

export interface CreditOrders {
  base_credits: number;
  bonus_credits: Generated<number>;
  bonus_kind: Generated<string>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  order_id: string;
  paid_at: Timestamp | null;
  price_idr: number;
  product_key: string;
  status: Generated<string>;
  total_credits: number;
  user_id: string;
}

export interface CreditOrdersV2 {
  amount_idr: Generated<number>;
  channel: string;
  created_at: Generated<Timestamp>;
  credits_base: Generated<number>;
  credits_bonus: Generated<number>;
  credits_total: Generated<number>;
  order_id: Generated<string>;
  order_number: string | null;
  product_id: string | null;
  product_key: string;
  purchase_token: string | null;
  status: Generated<string>;
  user_id: string;
  verified_at: Timestamp | null;
}

export interface CreditProducts {
  active: Generated<boolean>;
  bonus_active: Generated<boolean>;
  channel: Generated<string>;
  credits: number;
  first_topup_bonus_credits: Generated<number>;
  marketing_badge: string | null;
  name: string;
  normal_bonus_credits: Generated<number>;
  play_sku: string | null;
  price_idr: number;
  product_key: string;
  sort_order: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface CreditReservations {
  amount: number;
  chapter_number: number | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  ref: string;
  reservation_kind: string;
  status: Generated<string>;
  story_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface FactsLedger {
  created_at: Generated<Timestamp>;
  established_chapter: Generated<number>;
  id: string;
  load_bearing: Generated<boolean>;
  paid_off: Generated<boolean>;
  salience: Generated<number>;
  statement: string;
  story_id: string;
  subject_character_id: string | null;
}

export interface FeatureCreditCosts {
  credits_required: number;
  feature_key: string;
  is_active: Generated<boolean>;
  metadata: Generated<Json>;
  pricing_version: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface GenerationJobAttempts {
  attempt_number: number;
  chapter_number: number;
  correlation_id: string;
  created_at: Generated<Timestamp>;
  elapsed_ms: Int8 | null;
  ended_at: Timestamp | null;
  error_code: string | null;
  id: Generated<string>;
  job_id: string;
  lease_age_ms: Int8 | null;
  lease_remaining_ms: Int8 | null;
  model_id: string | null;
  provider_id: string | null;
  retry_decision: string | null;
  started_at: Timestamp;
  story_id: string;
  worker_id: string | null;
  workflow_phase: string;
}

export interface GenerationJobs {
  attempt_count: Generated<number>;
  available_at: Generated<Timestamp>;
  chapter_number: number;
  claim_token: string | null;
  claimed_at: Timestamp | null;
  /**
   * SHA-256 hex of canonical closure set. NULL until publication succeeds.
   */
  closure_payload_hash: string | null;
  completed_at: Timestamp | null;
  correlation_id: Generated<string>;
  created_at: Generated<Timestamp>;
  deadline_at: Timestamp;
  generation_kind: string;
  heartbeat_at: Timestamp | null;
  id: Generated<string>;
  last_error_at: Timestamp | null;
  last_error_class: string | null;
  last_error_code: string | null;
  max_attempts: Generated<number>;
  publication_idempotency_key: string;
  /**
   * SHA-256 hex of canonical publication payload. NULL until publication succeeds.
   */
  publication_payload_hash: string | null;
  publication_result: Json | null;
  status: string;
  /**
   * Snapshot of stories.story_contract_version at enqueue time. Immutable after insert.
   */
  story_contract_version: number | null;
  story_id: string;
  trigger_choice_id: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
  worker_id: string | null;
}

export interface GenerationLeases {
  chapter_number: number;
  claim_token: string | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  holder: string;
  id: Generated<string>;
  job_id: string | null;
  status: Generated<string>;
  story_id: string;
}

export interface GenerationModelPricingVersions {
  created_at: Generated<Timestamp>;
  created_by: string;
  currency: string;
  effective_from: Timestamp;
  effective_to: Timestamp | null;
  id: Generated<string>;
  input_token_price: Numeric;
  model_id: string;
  output_token_price: Numeric;
  provider_id: string;
  unit_size: Int8;
}

export interface GenerationPolicy {
  generation_max_queue: Generated<number>;
  id: Generated<number>;
  lease_ttl_seconds: Generated<number>;
  max_concurrent_generations: Generated<number>;
  max_concurrent_generations_per_user: Generated<number>;
  target_scenes: Generated<number>;
  target_words_max: Generated<number>;
  target_words_min: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface GenerationProviderCallDaily {
  call_count: Int8;
  cost_amount_sum: Numeric;
  cost_currency: string | null;
  cost_source: string;
  day: Timestamp;
  elapsed_ms_max: Int8;
  elapsed_ms_sum: Numeric;
  fallback_call_count: Int8;
  generation_kind: string | null;
  input_token_count_sum: Numeric;
  model_id: string;
  outcome: string;
  output_token_count_sum: Numeric;
  priced_call_count: Int8;
  provider_id: string;
  success_count: Int8;
  total_token_count_sum: Numeric;
  unavailable_cost_count: Int8;
  use_case: string;
  workflow_phase: string;
}

export interface GenerationProviderCalls {
  actual_model_resolved: boolean;
  attempt_number: number | null;
  chapter_number: number | null;
  correlation_id: string;
  cost_amount: Numeric | null;
  cost_currency: string | null;
  cost_source: string;
  created_at: Generated<Timestamp>;
  elapsed_ms: Generated<Int8>;
  ended_at: Generated<Timestamp>;
  error_code: string | null;
  fallback_index: number;
  generation_kind: string | null;
  id: Generated<string>;
  input_token_count: Int8 | null;
  job_id: string | null;
  model_id: string;
  outcome: string;
  output_token_count: Int8 | null;
  pricing_version_id: string | null;
  provider_call_id: string;
  provider_id: string;
  route_version: string | null;
  started_at: Timestamp;
  story_id: string;
  total_token_count: Int8 | null;
  use_case: string;
  user_id: string;
  validation_codes: string[] | null;
  validation_stage: string | null;
  workflow_phase: string;
}

export interface IdempotencyKeys {
  created_at: Generated<Timestamp>;
  key: string;
  result: Json | null;
  scope: string;
  story_id: string;
}

export interface KnowledgeScopes {
  character_id: string;
  created_at: Generated<Timestamp>;
  fact_id: string;
  id: Generated<Int8>;
  known_from_chapter: Generated<number>;
  story_id: string;
}

export interface MissionPolicy {
  ad_batch_credits: Generated<number>;
  ad_daily_cap: Generated<number>;
  ad_reward_enabled: Generated<boolean>;
  ads_per_credit: Generated<number>;
  adsense_client_id: Generated<string>;
  adsense_enabled: Generated<boolean>;
  adsense_slot_beranda: Generated<string>;
  adsense_slot_credit: Generated<string>;
  adsense_slot_ending: Generated<string>;
  adsense_slot_share_landing: Generated<string>;
  checkin_credits: Generated<number>;
  choice_credits: Generated<number>;
  choice_required: Generated<number>;
  id: Generated<boolean>;
  missions_enabled: Generated<boolean>;
  ssv_freshness_seconds: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface NeonSchemaMigrations {
  applied_at: Generated<Timestamp>;
  version: string;
}

export interface Outbox {
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  payload: Generated<Json>;
  processed_at: Timestamp | null;
  topic: string;
}

export interface PasswordRecoveryCapabilities {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  session_id: string;
  token_hash: Buffer;
  used_at: Timestamp | null;
  user_id: string;
}

export interface PersonalizedChoiceApplications {
  chapter_number: number;
  choice_id: string;
  created_at: Generated<Timestamp>;
  outcome_snapshot: Json;
  story_id: string;
  user_id: string;
}

export interface PersonalizedChoiceIdempotencyKeys {
  chapter_number: number;
  choice_id: string;
  created_at: Generated<Timestamp>;
  idempotency_key: string;
  story_id: string;
  user_id: string;
}

export interface PrivateE5ValidatorAttestationKey {
  signing_key: Generated<Buffer>;
  singleton: Generated<boolean>;
}

export interface PrivateGenerationIncidentAccessAudit {
  action: string;
  actor_user_id: string | null;
  capture_id: string;
  correlation_id: string;
  id: Generated<string>;
  occurred_at: Generated<Timestamp>;
}

export interface PrivateGenerationIncidentCaptures {
  auth_tag: string;
  capture_id: string;
  chapter_number: number;
  choice_index: number;
  ciphertext: string;
  claim_expires_at: Timestamp | null;
  claim_token: string | null;
  claimed_at: Timestamp | null;
  claimed_by: string | null;
  code: string;
  consumed_at: Timestamp | null;
  correlation_id: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  incident_key: string;
  label_fingerprint: string;
  nonce: string;
  stage: string;
  story_id: string;
  version: number;
}

export interface PushDevices {
  consent_at: Generated<Timestamp>;
  created_at: Generated<Timestamp>;
  fcm_token: string;
  id: Generated<string>;
  last_seen_at: Generated<Timestamp>;
  platform: string;
  user_id: string;
}

export interface PushLog {
  audience: string;
  body: string;
  created_at: Generated<Timestamp>;
  dedupe_key: string | null;
  deep_link: string | null;
  failure_count: Generated<number>;
  id: Generated<string>;
  sent_by: string | null;
  status: Generated<string>;
  success_count: Generated<number>;
  title: string;
}

export interface ReaderPlotDebtClosures {
  closed_at_chapter: number;
  /**
   * Worker provenance; NULL when the closure was recorded by the sync path (no generation job).
   */
  closed_by_job_id: string | null;
  closure_form: string;
  closure_version: Generated<number>;
  created_at: Generated<Timestamp>;
  debt_id: string;
  id: Generated<string>;
  story_id: string;
  user_id: string;
}

export interface ReaderPlotDebtProgress {
  created_at: Generated<Timestamp>;
  debt_id: string;
  milestone_chapter: number;
  progress_version: Generated<number>;
  progressed_at_chapter: number;
  /**
   * Worker provenance; NULL when progress was recorded by the sync path (no generation job).
   */
  source_job_id: string | null;
  story_id: string;
  user_id: string;
}

export interface ReaderStates {
  choice_history: Generated<Json>;
  created_at: Generated<Timestamp>;
  current_chapter: Generated<number>;
  ending_name: string | null;
  jejak: Generated<Json>;
  locked_ending_key: string | null;
  route_state: Generated<Json>;
  status: Generated<string>;
  story_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface ReaderTasteProfiles {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  taste_json: Generated<Json>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface ReadingPolicy {
  credits_per_chapter: Generated<number>;
  free_chapters: Generated<number>;
  id: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface ReferralAttributions {
  attributed_at: Generated<Timestamp>;
  id: Generated<string>;
  referred_user_id: string;
  referrer_user_id: string;
  shared_link_id: string | null;
  source: Generated<string>;
  window_ends_at: Timestamp;
}

export interface ReferralCodes {
  code: string;
  created_at: Generated<Timestamp>;
  user_id: string;
}

export interface RetrievalLogs {
  budget_report: Generated<Json>;
  created_at: Generated<Timestamp>;
  excluded_ids: Generated<Json>;
  id: Generated<Int8>;
  included_ids: Generated<Json>;
  story_id: string;
  target_chapter: number;
}

export interface RewardLedger {
  created_at: Generated<Timestamp>;
  delta_idr: number;
  id: Generated<string>;
  reason: string;
  ref: string;
  user_id: string;
}

export interface RewardPolicy {
  attribution_cookie_days: Generated<number>;
  commission_enabled: Generated<boolean>;
  commission_percent: Generated<number>;
  id: Generated<boolean>;
  payout_enabled: Generated<boolean>;
  payout_min_idr: Generated<number>;
  redeem_enabled: Generated<boolean>;
  redeem_min_idr: Generated<number>;
  redeem_rate_idr_per_credit: Generated<number>;
  updated_at: Generated<Timestamp>;
  window_days: Generated<number>;
}

export interface SecretsReveals {
  created_at: Generated<Timestamp>;
  description: string;
  id: string;
  reveal_gate_chapter: number;
  revealed: Generated<boolean>;
  story_id: string;
}

export interface SharedStoryLinks {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp | null;
  id: Generated<string>;
  owner_user_id: string;
  revoked_at: Timestamp | null;
  share_slug: string;
  share_type: Generated<string>;
  source_story_id: string;
  spoiler_level: Generated<string>;
  /**
   * Public-safe payload only: title, tagline, tropes, cover, endingName, bigChoices, cta.
   */
  teaser_json: Generated<Json>;
  title: string;
  visibility: Generated<string>;
}

export interface SharedStoryStarts {
  id: Generated<string>;
  new_story_id: string | null;
  new_user_id: string;
  shared_link_id: string;
  started_at: Generated<Timestamp>;
}

export interface Stories {
  /**
   * Monotonic committed-state revision. 0 = never committed. NOT incremented in A1b; first increment is atomic in A1c.
   */
  canon_state_revision: Generated<Int8>;
  commercial_origin: string | null;
  cover: Generated<string>;
  created_at: Generated<Timestamp>;
  current_chapter: Generated<number>;
  ending_name: string | null;
  generation_status: Generated<string>;
  id: string;
  jejak: Generated<Json>;
  /**
   * Living canon capability. 0 = legacy story, 1 = living canon enabled. Fail-closed IN (0,1).
   */
  living_canon_version: Generated<number>;
  /**
   * Playthrough owner (AMENDMENTS v0.5). Null = orphan/demo/legacy.
   */
  owner_user_id: string | null;
  role: Generated<string>;
  source_story_id: string | null;
  status: Generated<string>;
  story_contract_version: Generated<number>;
  story_mode: Generated<string>;
  synopsis: Generated<string>;
  tagline: Generated<string>;
  title: string;
  total_chapters: Generated<number>;
  tropes: Generated<Json>;
  /**
   * private | unlisted | public. Jelajahi lists official demos + public shares later.
   */
  visibility: Generated<string>;
}

export interface StoryCoverCandidates {
  created_at: Generated<Timestamp>;
  expires_at: Generated<Timestamp>;
  id: Generated<string>;
  preset: Generated<string>;
  story_id: string;
  url: string;
  user_id: string;
}

export interface StoryCreationRequests {
  created_at: Generated<Timestamp>;
  error_code: string | null;
  generation_job_id: string | null;
  idempotency_key: string;
  owner_user_id: string;
  request_hash: string;
  request_kind: string;
  status: string;
  story_id: string;
  updated_at: Generated<Timestamp>;
}

export interface StoryCreativeDirections {
  created_at: Generated<Timestamp>;
  direction_fingerprint: string;
  direction_json: Json;
  owner_user_id: string;
  prompt_contract_version: string;
  story_id: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface StoryEvents {
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  payload: Generated<Json>;
  seq: number;
  story_id: string;
  type: string;
}

export interface StoryGenerationContracts {
  bootstrap_payload_hash: string | null;
  contract_source: Generated<string>;
  created_at: Generated<Timestamp>;
  ending_candidates_json: Generated<Json>;
  ending_lock_json: Json | null;
  mode: string;
  onboarding_json: Generated<Json>;
  plot_debts_json: Generated<Json>;
  quality_profile: Generated<string>;
  route_schema_json: Generated<Json>;
  story_contract_json: Generated<Json>;
  /**
   * Contract version; V4 requires job = checkpoint = story = contract to match.
   */
  story_contract_version: number;
  story_id: string;
  total_chapters: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface StoryThreads {
  created_at: Generated<Timestamp>;
  id: string;
  is_main_mystery: Generated<boolean>;
  last_touched_chapter: Generated<number>;
  opened_chapter: Generated<number>;
  payoff_window: number | null;
  stale: Generated<boolean>;
  stale_since_chapter: number | null;
  status: Generated<string>;
  story_id: string;
  title: string;
}

export interface TimelineEvents {
  chapter_number: number;
  created_at: Generated<Timestamp>;
  description: string;
  id: Generated<Int8>;
  is_flashback: Generated<boolean>;
  occurs_at: number | null;
  ordinal: Generated<number>;
  story_id: string;
}

export interface TintaLedger {
  created_at: Generated<Timestamp>;
  delta: number;
  id: Generated<string>;
  pending_until: Timestamp | null;
  reason: string;
  ref: string;
  user_id: string;
}

export interface TintaPolicy {
  author_daily_cap: Generated<number>;
  author_rewards_enabled: Generated<boolean>;
  exchange_enabled: Generated<boolean>;
  exchange_min_lakoin: Generated<number>;
  id: Generated<boolean>;
  missions_pay_tinta: Generated<boolean>;
  pending_hours: Generated<number>;
  tinta_ad_batch: Generated<number>;
  tinta_checkin: Generated<number>;
  tinta_choice: Generated<number>;
  tinta_per_lakoin: Generated<number>;
  tinta_per_read: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface UserMissionDaily {
  claimed_at: Generated<Timestamp>;
  credits_granted: Generated<number>;
  day_jkt: Timestamp;
  mission_key: string;
  progress: Generated<number>;
  user_id: string;
}

export interface VwBlueprintPendingReviewItems {
  act_boundary: string | null;
  chapter_numbers: number[] | null;
  findings: Json | null;
  queue_created_at: Timestamp | null;
  role: string | null;
  source_event_id: string | null;
  story_id: string | null;
  story_status: string | null;
  story_title: string | null;
  tagline: string | null;
  total_chapters: number | null;
}

export interface VwBlueprintRecentResolutions {
  chapter_numbers: number[] | null;
  disposition: string | null;
  reason_text: string | null;
  resolution_created_at: Timestamp | null;
  resolution_id: string | null;
  result_chapter_version_pairs: Json | null;
  reviewer_email: string | null;
  reviewer_uid: string | null;
  source_event_id: string | null;
  story_id: string | null;
  story_title: string | null;
}

export interface VwBlueprintReviewAuthority {
  chapter_numbers: number[] | null;
  source_event_id: string | null;
  status: string | null;
  story_id: string | null;
}

export interface VwBlueprintReviewItemDetails {
  act_boundary: string | null;
  audit_entries: Json | null;
  brand_scan_hash: string | null;
  chapter_numbers: number[] | null;
  claimed_at: Timestamp | null;
  claimed_by: string | null;
  created_at: Timestamp | null;
  findings: Json | null;
  lease_id: string | null;
  provider_call_id: string | null;
  recent_resolutions: Json | null;
  retry_count: number | null;
  source_event_id: string | null;
  status: string | null;
  story_id: string | null;
  story_title: string | null;
  tagline: string | null;
}

export interface DB {
  account_commercial_states: AccountCommercialStates;
  act_rollups: ActRollups;
  admin_credit_grants: AdminCreditGrants;
  admin_generation_access_audit: AdminGenerationAccessAudit;
  admin_settings_audit_logs: AdminSettingsAuditLogs;
  admin_users: AdminUsers;
  admob_ssv_events: AdmobSsvEvents;
  ai_model_routes: AiModelRoutes;
  analytics_events: AnalyticsEvents;
  "auth.users": AuthUsers;
  blueprint_audit_log: BlueprintAuditLog;
  blueprint_queue: BlueprintQueue;
  blueprint_resolutions: BlueprintResolutions;
  blueprint_validator_attestations: BlueprintValidatorAttestations;
  blueprint_validator_proofs: BlueprintValidatorProofs;
  chapter_blueprints: ChapterBlueprints;
  chapter_generation_checkpoints: ChapterGenerationCheckpoints;
  chapter_state_commits: ChapterStateCommits;
  chapters: Chapters;
  character_aliases: CharacterAliases;
  character_states: CharacterStates;
  character_voice_sheets: CharacterVoiceSheets;
  characters: Characters;
  choice_outcomes: ChoiceOutcomes;
  commercial_generation_intents: CommercialGenerationIntents;
  content_reports: ContentReports;
  credit_ledger: CreditLedger;
  credit_orders: CreditOrders;
  credit_orders_v2: CreditOrdersV2;
  credit_products: CreditProducts;
  credit_reservations: CreditReservations;
  facts_ledger: FactsLedger;
  feature_credit_costs: FeatureCreditCosts;
  generation_job_attempts: GenerationJobAttempts;
  generation_jobs: GenerationJobs;
  generation_leases: GenerationLeases;
  generation_model_pricing_versions: GenerationModelPricingVersions;
  generation_policy: GenerationPolicy;
  generation_provider_call_daily: GenerationProviderCallDaily;
  generation_provider_calls: GenerationProviderCalls;
  idempotency_keys: IdempotencyKeys;
  knowledge_scopes: KnowledgeScopes;
  mission_policy: MissionPolicy;
  neon_schema_migrations: NeonSchemaMigrations;
  outbox: Outbox;
  password_recovery_capabilities: PasswordRecoveryCapabilities;
  personalized_choice_applications: PersonalizedChoiceApplications;
  personalized_choice_idempotency_keys: PersonalizedChoiceIdempotencyKeys;
  "private.e5_validator_attestation_key": PrivateE5ValidatorAttestationKey;
  "private.generation_incident_access_audit": PrivateGenerationIncidentAccessAudit;
  "private.generation_incident_captures": PrivateGenerationIncidentCaptures;
  push_devices: PushDevices;
  push_log: PushLog;
  reader_plot_debt_closures: ReaderPlotDebtClosures;
  reader_plot_debt_progress: ReaderPlotDebtProgress;
  reader_states: ReaderStates;
  reader_taste_profiles: ReaderTasteProfiles;
  reading_policy: ReadingPolicy;
  referral_attributions: ReferralAttributions;
  referral_codes: ReferralCodes;
  retrieval_logs: RetrievalLogs;
  reward_ledger: RewardLedger;
  reward_policy: RewardPolicy;
  secrets_reveals: SecretsReveals;
  shared_story_links: SharedStoryLinks;
  shared_story_starts: SharedStoryStarts;
  stories: Stories;
  story_cover_candidates: StoryCoverCandidates;
  story_creation_requests: StoryCreationRequests;
  story_creative_directions: StoryCreativeDirections;
  story_events: StoryEvents;
  story_generation_contracts: StoryGenerationContracts;
  story_threads: StoryThreads;
  timeline_events: TimelineEvents;
  tinta_ledger: TintaLedger;
  tinta_policy: TintaPolicy;
  user_mission_daily: UserMissionDaily;
  vw_blueprint_pending_review_items: VwBlueprintPendingReviewItems;
  vw_blueprint_recent_resolutions: VwBlueprintRecentResolutions;
  vw_blueprint_review_authority: VwBlueprintReviewAuthority;
  vw_blueprint_review_item_details: VwBlueprintReviewItemDetails;
}

export type Database = DB
